site_name: SGPF - Sistema de Gestão de Pesquisa Florestal

nav:
  - Início: index.md
  - Tutoriais:
      - Primeiros Passos: ApresentacaoArgow.md
      - Cadastro de um novo experimento: cadastroExperimento.md
      - Atualizar dados do experimento: AlteracaoCadastroExperimento.md
      - Complementar características: caracExperimentos.md
      - Exportar resultados: exportTable.md

theme:
  name: material
  logo: images/esalq-icon.jpg
  favicon: images/esalq-icon.jpg

extra_css:
  - stylesheets/extra.css
